"""add diteruskan_ke_warehouse fields to fkp_resolutions

Revision ID: 007b6472ca70
Revises: 654f31003e05
Create Date: 2026-09-17 13:32:34.798825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '007b6472ca70'
down_revision: Union[str, None] = '654f31003e05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # [FIX] server_default diperlukan supaya baris LAMA yang sudah ada di
    # fkp_resolutions kebagian nilai default saat kolom NOT NULL ditambahkan.
    # Tanpa ini Postgres menolak ALTER TABLE dengan NotNullViolation.
    op.add_column(
        'fkp_resolutions',
        sa.Column('diteruskan_ke_warehouse', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.add_column('fkp_resolutions', sa.Column('tanggal_diteruskan_ke_warehouse', sa.DateTime(timezone=True), nullable=True))
    op.add_column('fkp_resolutions', sa.Column('diteruskan_oleh', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'fkp_resolutions', 'users', ['diteruskan_oleh'], ['id'])
    # [FIX] Lepas server_default setelah backfill — kolom tetap NOT NULL,
    # tapi default-nya biar dipegang aplikasi (model Python), bukan DB.
    # Opsional untuk dilewati kalau memang mau DB yang pegang default-nya.
    op.alter_column('fkp_resolutions', 'diteruskan_ke_warehouse', server_default=None)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'fkp_resolutions', type_='foreignkey')
    op.drop_column('fkp_resolutions', 'diteruskan_oleh')
    op.drop_column('fkp_resolutions', 'tanggal_diteruskan_ke_warehouse')
    op.drop_column('fkp_resolutions', 'diteruskan_ke_warehouse')
    # ### end Alembic commands ###