"""add kode field to wilayah tables

Revision ID: 0c5822ed869f
Revises: b54d8d49a2d2
Create Date: 2026-05-08 15:14:41.333418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0c5822ed869f'
down_revision: Union[str, None] = 'b54d8d49a2d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ── kabupaten_kota ───────────────────────────────────────
    op.add_column('kabupaten_kota', sa.Column('kode', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True))
    op.execute("UPDATE kabupaten_kota SET kode = CAST(id AS VARCHAR) WHERE kode IS NULL")
    op.alter_column('kabupaten_kota', 'kode', nullable=False)
    op.create_index(op.f('ix_kabupaten_kota_kode'), 'kabupaten_kota', ['kode'], unique=True)
    op.drop_column('kabupaten_kota', 'tipe')

    # ── kecamatan ────────────────────────────────────────────
    op.add_column('kecamatan', sa.Column('kode', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True))
    op.execute("UPDATE kecamatan SET kode = CAST(id AS VARCHAR) WHERE kode IS NULL")
    op.alter_column('kecamatan', 'kode', nullable=False)
    op.create_index(op.f('ix_kecamatan_kode'), 'kecamatan', ['kode'], unique=True)

    # ── kelurahan ────────────────────────────────────────────
    op.add_column('kelurahan', sa.Column('kode', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True))
    op.execute("UPDATE kelurahan SET kode = CAST(id AS VARCHAR) WHERE kode IS NULL")
    op.alter_column('kelurahan', 'kode', nullable=False)
    op.create_index(op.f('ix_kelurahan_kode'), 'kelurahan', ['kode'], unique=True)

    # ── provinsi ─────────────────────────────────────────────
    op.add_column('provinsi', sa.Column('kode', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True))
    op.execute("UPDATE provinsi SET kode = CAST(id AS VARCHAR) WHERE kode IS NULL")
    op.alter_column('provinsi', 'kode', nullable=False)
    op.create_index(op.f('ix_provinsi_kode'), 'provinsi', ['kode'], unique=True)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_provinsi_kode'), table_name='provinsi')
    op.drop_column('provinsi', 'kode')
    op.drop_index(op.f('ix_kelurahan_kode'), table_name='kelurahan')
    op.drop_column('kelurahan', 'kode')
    op.drop_index(op.f('ix_kecamatan_kode'), table_name='kecamatan')
    op.drop_column('kecamatan', 'kode')
    op.add_column('kabupaten_kota', sa.Column('tipe', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_kabupaten_kota_kode'), table_name='kabupaten_kota')
    op.drop_column('kabupaten_kota', 'kode')
    # ### end Alembic commands ###
