"""add_index_to_fkp_attachments_fkp_item_id

Revision ID: 195d6425f1e0
Revises: 8f4dcdb23921
Create Date: 2026-04-27 09:48:25.543253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '195d6425f1e0'
down_revision: Union[str, None] = '8f4dcdb23921'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_fkp_attachments_fkp_item_id'), 'fkp_attachments', ['fkp_item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fkp_attachments_fkp_item_id'), table_name='fkp_attachments')
    # ### end Alembic commands ###
