"""rating_testimoni_not_null

Revision ID: 41719a28ab0c
Revises: e48ecff4c0c5
Create Date: 2026-05-26 16:25:04.268854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '41719a28ab0c'
down_revision: Union[str, None] = 'e48ecff4c0c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fkp_testimoni', 'rating_kecepatan',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('fkp_testimoni', 'rating_komunikasi',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('fkp_testimoni', 'rating_solusi',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('fkp_testimoni', 'rating_aplikasi',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fkp_testimoni', 'rating_aplikasi',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('fkp_testimoni', 'rating_solusi',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('fkp_testimoni', 'rating_komunikasi',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('fkp_testimoni', 'rating_kecepatan',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
