"""add role finance and modify fkpattachment

Revision ID: 446408070d08
Revises: bdffe163b717
Create Date: 2026-04-30 19:23:13.737457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '446408070d08'
down_revision: Union[str, None] = 'bdffe163b717'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fkp_attachments', sa.Column('tipe_dokumen', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True))

    op.execute("""
        UPDATE fkp_attachments
        SET tipe_dokumen = 'image'
    """)
    
    op.alter_column('fkp_attachments', 'tipe_dokumen', nullable=False)
    op.add_column('fkp_attachments', sa.Column('keterangan', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('fkp_resolutions', sa.Column('catatan_finance', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    
    op.add_column('fkp_resolutions', sa.Column('diproses_finance', sa.Boolean(), nullable=True))
    
    op.execute("""
        UPDATE fkp_resolutions
        SET diproses_finance = False
    """)
    
    op.alter_column('fkp_resolutions', 'diproses_finance', nullable=False)
    
    op.alter_column('fkp_attachments', 'tipe_dokumen', nullable=False)
    op.add_column('fkp_resolutions', sa.Column('tanggal_proses_finance', sa.DateTime(timezone=True), nullable=True))
    op.add_column('fkp_resolutions', sa.Column('finance_user_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'fkp_resolutions', 'users', ['finance_user_id'], ['id'])
    op.drop_column('fkp_resolutions', 'detail_item')
    op.drop_column('fkp_resolutions', 'bukti_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fkp_resolutions', sa.Column('bukti_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('fkp_resolutions', sa.Column('detail_item', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'fkp_resolutions', type_='foreignkey')
    op.drop_column('fkp_resolutions', 'finance_user_id')
    op.drop_column('fkp_resolutions', 'tanggal_proses_finance')
    op.drop_column('fkp_resolutions', 'diproses_finance')
    op.drop_column('fkp_resolutions', 'catatan_finance')
    op.drop_column('fkp_attachments', 'keterangan')
    op.drop_column('fkp_attachments', 'tipe_dokumen')
    # ### end Alembic commands ###
