"""add rekomendasi fields to fkp_items

Revision ID: 459bd026a44b
Revises: a9549e693e52
Create Date: 2026-05-19 09:13:15.899454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '459bd026a44b'
down_revision: Union[str, None] = 'a9549e693e52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fkp_items', sa.Column('rekomendasi_penanganan_apsm', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('fkp_items', sa.Column('rekomendasi_kompensasi_apsm', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('fkp_items', sa.Column('rekomendasi_penanganan_admin_ho', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('fkp_items', sa.Column('rekomendasi_kompensasi_admin_ho', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('fkp_items', 'rekomendasi_apsm')
    op.drop_column('fkp_items', 'rekomendasi_admin_ho')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fkp_items', sa.Column('rekomendasi_admin_ho', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    op.add_column('fkp_items', sa.Column('rekomendasi_apsm', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    op.drop_column('fkp_items', 'rekomendasi_kompensasi_admin_ho')
    op.drop_column('fkp_items', 'rekomendasi_penanganan_admin_ho')
    op.drop_column('fkp_items', 'rekomendasi_kompensasi_apsm')
    op.drop_column('fkp_items', 'rekomendasi_penanganan_apsm')
    # ### end Alembic commands ###
