"""add kondisi_sample_lainnya dan approved_by_rsm_final ke fkp

Revision ID: 654f31003e05
Revises: 788b6f1ff53d
Create Date: 2026-09-17 08:42:20.162239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '654f31003e05'
down_revision: Union[str, None] = '788b6f1ff53d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fkp_complaints', sa.Column('approved_by_rsm_final', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'fkp_complaints', 'users', ['approved_by_rsm_final'], ['id'])
    op.add_column('fkp_items', sa.Column('kondisi_sample_lainnya', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fkp_items', 'kondisi_sample_lainnya')
    op.drop_constraint(None, 'fkp_complaints', type_='foreignkey')
    op.drop_column('fkp_complaints', 'approved_by_rsm_final')
    # ### end Alembic commands ###
