"""product_id wajib, drop nama_produk_custom, add qty_per_kemasan

Revision ID: 6ef69e8db49c
Revises: 007b6472ca70
Create Date: 2026-09-22 17:37:18.000021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6ef69e8db49c'
down_revision: Union[str, None] = '007b6472ca70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fkp_items', 'product_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_index(op.f('ix_fkp_items_product_id'), 'fkp_items', ['product_id'], unique=False)
    op.drop_column('fkp_items', 'nama_produk_custom')
    op.add_column('product_catalog', sa.Column('qty_per_kemasan', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_catalog', 'qty_per_kemasan')
    op.add_column('fkp_items', sa.Column('nama_produk_custom', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_fkp_items_product_id'), table_name='fkp_items')
    op.alter_column('fkp_items', 'product_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
