"""add fkp_bapkp tables

Revision ID: 788b6f1ff53d
Revises: 7ce1b01b936b
Create Date: 2026-08-10 11:12:47.072983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '788b6f1ff53d'
down_revision: Union[str, None] = '7ce1b01b936b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fkp_bapkp',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('fkp_id', sa.Uuid(), nullable=False),
    sa.Column('nomor_ba', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hari_pemeriksaan', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tanggal_pemeriksaan', sa.Date(), nullable=True),
    sa.Column('tanggal_diterima_qc', sa.Date(), nullable=True),
    sa.Column('catatan_pemeriksaan', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('dibuat_oleh', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['dibuat_oleh'], ['users.id'], ),
    sa.ForeignKeyConstraint(['fkp_id'], ['fkp_complaints.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fkp_bapkp_fkp_id'), 'fkp_bapkp', ['fkp_id'], unique=True)
    op.create_index(op.f('ix_fkp_bapkp_nomor_ba'), 'fkp_bapkp', ['nomor_ba'], unique=True)
    op.create_table('fkp_bapkp_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('bapkp_id', sa.Uuid(), nullable=False),
    sa.Column('fkp_item_id', sa.Uuid(), nullable=False),
    sa.Column('tanggal_kadaluarsa', sa.Date(), nullable=True),
    sa.Column('umur_produk', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tanggal_dikirim', sa.Date(), nullable=True),
    sa.Column('lama_di_gudang_spp', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['bapkp_id'], ['fkp_bapkp.id'], ),
    sa.ForeignKeyConstraint(['fkp_item_id'], ['fkp_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fkp_bapkp_items_bapkp_id'), 'fkp_bapkp_items', ['bapkp_id'], unique=False)
    op.create_index(op.f('ix_fkp_bapkp_items_fkp_item_id'), 'fkp_bapkp_items', ['fkp_item_id'], unique=False)
    op.alter_column('sample_shipments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('sample_shipments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('sample_status_logs', 'changed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('warehouse_surat_jalan', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('warehouse_surat_jalan', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_index('ix_wsj_fkp_status', table_name='warehouse_surat_jalan')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_wsj_fkp_status', 'warehouse_surat_jalan', ['fkp_id', 'status'], unique=False)
    op.alter_column('warehouse_surat_jalan', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('warehouse_surat_jalan', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('sample_status_logs', 'changed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('sample_shipments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('sample_shipments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_index(op.f('ix_fkp_bapkp_items_fkp_item_id'), table_name='fkp_bapkp_items')
    op.drop_index(op.f('ix_fkp_bapkp_items_bapkp_id'), table_name='fkp_bapkp_items')
    op.drop_table('fkp_bapkp_items')
    op.drop_index(op.f('ix_fkp_bapkp_nomor_ba'), table_name='fkp_bapkp')
    op.drop_index(op.f('ix_fkp_bapkp_fkp_id'), table_name='fkp_bapkp')
    op.drop_table('fkp_bapkp')
    # ### end Alembic commands ###
