"""add_fkp_items_revisi_state_machine

Revision ID: 8598560622a2
Revises: e682f38b3809
Create Date: 2026-04-24 21:44:35.683696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8598560622a2'
down_revision: Union[str, None] = 'e682f38b3809'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fkp_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('fkp_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=True),
    sa.Column('nama_produk_custom', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('jenis_kemasan', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('qty_zak', sa.Integer(), nullable=False),
    sa.Column('qty_dus', sa.Integer(), nullable=False),
    sa.Column('qty_renceng', sa.Integer(), nullable=False),
    sa.Column('batch_number', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('expired_date', sa.Date(), nullable=True),
    sa.Column('ada_sample_keluhan', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('ada_foto_sample', sa.Boolean(), nullable=False),
    sa.Column('lokasi_pembelian', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('tanggal_pembelian', sa.Date(), nullable=True),
    sa.Column('tanggal_dikonsumsi', sa.Date(), nullable=True),
    sa.Column('jenis_keluhan', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('deskripsi_keluhan', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('rekomendasi_apsm', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=True),
    sa.Column('catatan_apsm', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('persentase_disetujui_apsm', sa.Integer(), nullable=True),
    sa.Column('rekomendasi_admin_ho', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=True),
    sa.Column('catatan_admin_ho', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('persentase_disetujui_admin_ho', sa.Integer(), nullable=True),
    sa.Column('status_item', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('catatan_qc', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('alasan_penolakan', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['fkp_id'], ['fkp_complaints.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product_catalog.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fkp_items_fkp_id'), 'fkp_items', ['fkp_id'], unique=False)
    op.add_column('fkp_attachments', sa.Column('fkp_item_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'fkp_attachments', 'fkp_items', ['fkp_item_id'], ['id'])
    op.add_column('fkp_complaints', sa.Column('catatan_rsm_investigasi', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('fkp_complaints', sa.Column('catatan_rsm_resolusi', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('fkp_complaints', 'prioritas',
               existing_type=sa.VARCHAR(length=10),
               type_=sqlmodel.sql.sqltypes.AutoString(length=20),
               existing_nullable=False)
    op.alter_column('fkp_complaints', 'status',
               existing_type=sa.VARCHAR(length=30),
               type_=sqlmodel.sql.sqltypes.AutoString(length=40),
               existing_nullable=False)
    op.drop_constraint('fkp_complaints_product_id_fkey', 'fkp_complaints', type_='foreignkey')
    op.drop_column('fkp_complaints', 'qty_dus')
    op.drop_column('fkp_complaints', 'expired_date')
    op.drop_column('fkp_complaints', 'jenis_keluhan')
    op.drop_column('fkp_complaints', 'product_id')
    op.drop_column('fkp_complaints', 'catatan_rsm')
    op.drop_column('fkp_complaints', 'sumber_ketidaksesuaian')
    op.drop_column('fkp_complaints', 'qty_renceng')
    op.drop_column('fkp_complaints', 'qty_zak')
    op.drop_column('fkp_complaints', 'batch_number')
    op.drop_column('fkp_complaints', 'deskripsi_keluhan')
    op.drop_column('fkp_complaints', 'jenis_kemasan')
    op.add_column('fkp_resolutions', sa.Column('detail_item', sa.JSON(), nullable=True))
    op.alter_column('fkp_status_logs', 'status_lama',
               existing_type=sa.VARCHAR(length=30),
               type_=sqlmodel.sql.sqltypes.AutoString(length=40),
               existing_nullable=True)
    op.alter_column('fkp_status_logs', 'status_baru',
               existing_type=sa.VARCHAR(length=30),
               type_=sqlmodel.sql.sqltypes.AutoString(length=40),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fkp_status_logs', 'status_baru',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=40),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    op.alter_column('fkp_status_logs', 'status_lama',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=40),
               type_=sa.VARCHAR(length=30),
               existing_nullable=True)
    op.drop_column('fkp_resolutions', 'detail_item')
    op.add_column('fkp_complaints', sa.Column('jenis_kemasan', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('fkp_complaints', sa.Column('deskripsi_keluhan', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('fkp_complaints', sa.Column('batch_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('fkp_complaints', sa.Column('qty_zak', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('fkp_complaints', sa.Column('qty_renceng', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('fkp_complaints', sa.Column('sumber_ketidaksesuaian', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('fkp_complaints', sa.Column('catatan_rsm', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('fkp_complaints', sa.Column('product_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('fkp_complaints', sa.Column('jenis_keluhan', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('fkp_complaints', sa.Column('expired_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('fkp_complaints', sa.Column('qty_dus', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('fkp_complaints_product_id_fkey', 'fkp_complaints', 'product_catalog', ['product_id'], ['id'])
    op.alter_column('fkp_complaints', 'status',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=40),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    op.alter_column('fkp_complaints', 'prioritas',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=20),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    op.drop_column('fkp_complaints', 'catatan_rsm_resolusi')
    op.drop_column('fkp_complaints', 'catatan_rsm_investigasi')
    op.drop_constraint(None, 'fkp_attachments', type_='foreignkey')
    op.drop_column('fkp_attachments', 'fkp_item_id')
    op.drop_index(op.f('ix_fkp_items_fkp_id'), table_name='fkp_items')
    op.drop_table('fkp_items')
    # ### end Alembic commands ###
