"""rbac dynamic permissions

Revision ID: 984c1c2d7b64
Revises: d414a41bafb3
Create Date: 2026-06-21 23:30:15.398672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '984c1c2d7b64'
down_revision: Union[str, None] = 'd414a41bafb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('module', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False),
    sa.Column('deskripsi', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permissions_code'), 'permissions', ['code'], unique=True)
    op.create_index(op.f('ix_permissions_module'), 'permissions', ['module'], unique=False)
    op.alter_column('outlets', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.add_column('role_permissions', sa.Column('permission_id', sa.Uuid(), nullable=False))
    op.create_index(op.f('ix_role_permissions_permission_id'), 'role_permissions', ['permission_id'], unique=False)
    op.create_unique_constraint('uq_role_permissions_role_permission', 'role_permissions', ['role_id', 'permission_id'])
    op.create_foreign_key(None, 'role_permissions', 'permissions', ['permission_id'], ['id'])
    op.drop_column('role_permissions', 'permission_code')

    op.add_column('roles', sa.Column(
        'is_superadmin',
        sa.Boolean(),
        nullable=False,
        server_default=sa.text('false')   # semua role existing → False by default
    ))

    op.execute("UPDATE roles SET is_superadmin = true WHERE kode_role = 'superadmin'")

    op.alter_column('roles', 'is_superadmin', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roles', 'is_superadmin')
    op.add_column('role_permissions', sa.Column('permission_code', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'role_permissions', type_='foreignkey')
    op.drop_constraint('uq_role_permissions_role_permission', 'role_permissions', type_='unique')
    op.drop_index(op.f('ix_role_permissions_permission_id'), table_name='role_permissions')
    op.drop_column('role_permissions', 'permission_id')
    op.alter_column('outlets', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'pending'::character varying"),
               existing_nullable=False)
    op.drop_index(op.f('ix_permissions_module'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_code'), table_name='permissions')
    op.drop_table('permissions')
    # ### end Alembic commands ###
