"""add_metode_penanganan_fisik_to_fkp_resolutions

Revision ID: a9549e693e52
Revises: 8b4de5d28db4
Create Date: 2026-05-18 14:03:06.993978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a9549e693e52'
down_revision: Union[str, None] = '8b4de5d28db4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fkp_resolutions',
        sa.Column('metode_penanganan_fisik', sa.String(30), nullable=True))
    op.add_column('fkp_resolutions',
        sa.Column('detail_penanganan', sa.String(255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fkp_resolutions', 'detail_penanganan')
    op.drop_column('fkp_resolutions', 'metode_penanganan_fisik')
    # ### end Alembic commands ###
