"""add kondisi_sample and approver fields to fkp

Revision ID: b54d8d49a2d2
Revises: 95df50a6776c
Create Date: 2026-05-05 16:58:39.678906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b54d8d49a2d2'
down_revision: Union[str, None] = '95df50a6776c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fkp_complaints', sa.Column('approved_by_marketing', sa.Uuid(), nullable=True))
    op.add_column('fkp_complaints', sa.Column('approved_by_direktur', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'fkp_complaints', 'users', ['approved_by_direktur'], ['id'])
    op.create_foreign_key(None, 'fkp_complaints', 'users', ['approved_by_marketing'], ['id'])
    op.add_column('fkp_items', sa.Column('kondisi_sample', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fkp_items', 'kondisi_sample')
    op.drop_constraint(None, 'fkp_complaints', type_='foreignkey')
    op.drop_constraint(None, 'fkp_complaints', type_='foreignkey')
    op.drop_column('fkp_complaints', 'approved_by_direktur')
    op.drop_column('fkp_complaints', 'approved_by_marketing')
    # ### end Alembic commands ###
