"""add bukti_url and fix qty default

Revision ID: bdffe163b717
Revises: 195d6425f1e0
Create Date: 2026-04-30 09:32:11.581404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bdffe163b717'
down_revision: Union[str, None] = '195d6425f1e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fkp_complaints', sa.Column('lokasi_pembelian', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('fkp_items', sa.Column('qty', sa.Integer(), nullable=True))

    op.execute("""
        UPDATE fkp_items
        SET qty = COALESCE(qty_zak, 0) + COALESCE(qty_dus, 0) + COALESCE(qty_renceng, 0)
    """)
    
    op.alter_column('fkp_items', 'qty', nullable=False)
    
    op.drop_column('fkp_items', 'qty_dus')
    op.drop_column('fkp_items', 'lokasi_pembelian')
    op.drop_column('fkp_items', 'qty_renceng')
    op.drop_column('fkp_items', 'qty_zak')
    op.add_column('fkp_resolutions', sa.Column('bukti_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True))
    op.drop_column('fkp_resolutions', 'foto_pemusnahan')
    op.add_column('product_catalog', sa.Column('foto_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_catalog', 'foto_url')
    op.add_column('fkp_resolutions', sa.Column('foto_pemusnahan', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('fkp_resolutions', 'bukti_url')
    op.add_column('fkp_items', sa.Column('qty_zak', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('fkp_items', sa.Column('qty_renceng', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('fkp_items', sa.Column('lokasi_pembelian', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('fkp_items', sa.Column('qty_dus', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('fkp_items', 'qty')
    op.drop_column('fkp_complaints', 'lokasi_pembelian')
    # ### end Alembic commands ###
