"""initial_schema

Revision ID: bfec5bdaa9b7
Revises: 
Create Date: 2026-04-13 13:04:19.177420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'bfec5bdaa9b7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_catalog',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('kode_produk', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('nama_produk', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('jenis_kemasan', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('berat_gr', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_catalog_kode_produk'), 'product_catalog', ['kode_produk'], unique=True)
    op.create_table('provinsi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama_provinsi', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_provinsi_nama_provinsi'), 'provinsi', ['nama_provinsi'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('kode_role', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('nama_role', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('deskripsi', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_kode_role'), 'roles', ['kode_role'], unique=True)
    op.create_table('kabupaten_kota',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provinsi_id', sa.Integer(), nullable=False),
    sa.Column('nama', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('tipe', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.ForeignKeyConstraint(['provinsi_id'], ['provinsi.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kabupaten_kota_provinsi_id'), 'kabupaten_kota', ['provinsi_id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('permission_code', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('keterangan', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_permissions_role_id'), 'role_permissions', ['role_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('nama', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('no_telepon', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_role_id'), 'users', ['role_id'], unique=False)
    op.create_table('areas',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('kode_area', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('nama_area', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('pic_user_id', sa.Uuid(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pic_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_areas_kode_area'), 'areas', ['kode_area'], unique=True)
    op.create_table('kecamatan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kabupaten_kota_id', sa.Integer(), nullable=False),
    sa.Column('nama', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.ForeignKeyConstraint(['kabupaten_kota_id'], ['kabupaten_kota.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kecamatan_kabupaten_kota_id'), 'kecamatan', ['kabupaten_kota_id'], unique=False)
    op.create_table('area_provinces',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('area_id', sa.Uuid(), nullable=False),
    sa.Column('provinsi_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ),
    sa.ForeignKeyConstraint(['provinsi_id'], ['provinsi.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_area_provinces_area_id'), 'area_provinces', ['area_id'], unique=False)
    op.create_index(op.f('ix_area_provinces_provinsi_id'), 'area_provinces', ['provinsi_id'], unique=False)
    op.create_table('kelurahan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kecamatan_id', sa.Integer(), nullable=False),
    sa.Column('nama', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('kode_pos', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.ForeignKeyConstraint(['kecamatan_id'], ['kecamatan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kelurahan_kecamatan_id'), 'kelurahan', ['kecamatan_id'], unique=False)
    op.create_table('distributors',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('area_id', sa.Uuid(), nullable=False),
    sa.Column('kelurahan_id', sa.Integer(), nullable=True),
    sa.Column('kode_distributor', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('nama_perusahaan', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('pemilik', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False),
    sa.Column('no_telepon', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('email_perusahaan', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=True),
    sa.Column('alamat_lengkap', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('kode_pos', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ),
    sa.ForeignKeyConstraint(['kelurahan_id'], ['kelurahan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_distributors_area_id'), 'distributors', ['area_id'], unique=False)
    op.create_index(op.f('ix_distributors_kode_distributor'), 'distributors', ['kode_distributor'], unique=True)
    op.create_table('distributor_users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('distributor_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('jabatan', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['distributor_id'], ['distributors.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_distributor_users_distributor_id'), 'distributor_users', ['distributor_id'], unique=False)
    op.create_index(op.f('ix_distributor_users_user_id'), 'distributor_users', ['user_id'], unique=False)
    op.create_table('fkp_complaints',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nomor_fkp', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('distributor_id', sa.Uuid(), nullable=False),
    sa.Column('submitted_by', sa.Uuid(), nullable=False),
    sa.Column('handled_by', sa.Uuid(), nullable=True),
    sa.Column('product_id', sa.Uuid(), nullable=True),
    sa.Column('jenis_kemasan', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('qty_zak', sa.Integer(), nullable=False),
    sa.Column('qty_dus', sa.Integer(), nullable=False),
    sa.Column('qty_renceng', sa.Integer(), nullable=False),
    sa.Column('batch_number', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('expired_date', sa.Date(), nullable=True),
    sa.Column('jenis_keluhan', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('deskripsi_keluhan', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('prioritas', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('catatan_distributor', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('catatan_apsm', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('catatan_admin', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('sumber_ketidaksesuaian', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('nomor_surat_jalan', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('tanggal_pengajuan', sa.DateTime(), nullable=True),
    sa.Column('tanggal_selesai', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['distributor_id'], ['distributors.id'], ),
    sa.ForeignKeyConstraint(['handled_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product_catalog.id'], ),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fkp_complaints_distributor_id'), 'fkp_complaints', ['distributor_id'], unique=False)
    op.create_index(op.f('ix_fkp_complaints_nomor_fkp'), 'fkp_complaints', ['nomor_fkp'], unique=True)
    op.create_index(op.f('ix_fkp_complaints_status'), 'fkp_complaints', ['status'], unique=False)
    op.create_table('fkp_attachments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('fkp_id', sa.Uuid(), nullable=False),
    sa.Column('tipe_file', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('nama_file', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('ukuran_bytes', sa.Integer(), nullable=True),
    sa.Column('uploaded_by', sa.Uuid(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['fkp_id'], ['fkp_complaints.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fkp_attachments_fkp_id'), 'fkp_attachments', ['fkp_id'], unique=False)
    op.create_table('fkp_documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('fkp_id', sa.Uuid(), nullable=False),
    sa.Column('tipe_dokumen', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('nomor_dokumen', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('tanggal_dokumen', sa.Date(), nullable=True),
    sa.Column('url_file', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('dibuat_oleh', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dibuat_oleh'], ['users.id'], ),
    sa.ForeignKeyConstraint(['fkp_id'], ['fkp_complaints.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fkp_documents_fkp_id'), 'fkp_documents', ['fkp_id'], unique=False)
    op.create_table('fkp_resolutions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('fkp_id', sa.Uuid(), nullable=False),
    sa.Column('tipe_resolusi', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('nilai_cashback', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('nama_bank', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('nomor_rekening', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('atas_nama', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=True),
    sa.Column('nomor_nota_retur', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('nomor_do', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('tanggal_pengiriman', sa.DateTime(), nullable=True),
    sa.Column('ekspedisi', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('resi_pengiriman', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('tanggal_pemusnahan', sa.Date(), nullable=True),
    sa.Column('lokasi_pemusnahan', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('foto_pemusnahan', sa.JSON(), nullable=True),
    sa.Column('keterangan', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('dibuat_oleh', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dibuat_oleh'], ['users.id'], ),
    sa.ForeignKeyConstraint(['fkp_id'], ['fkp_complaints.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fkp_resolutions_fkp_id'), 'fkp_resolutions', ['fkp_id'], unique=True)
    op.create_table('fkp_status_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('fkp_id', sa.Uuid(), nullable=False),
    sa.Column('status_lama', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=True),
    sa.Column('status_baru', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('catatan', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('changed_by', sa.Uuid(), nullable=False),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['fkp_id'], ['fkp_complaints.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fkp_status_logs_fkp_id'), 'fkp_status_logs', ['fkp_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('fkp_id', sa.Uuid(), nullable=True),
    sa.Column('judul', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('pesan', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tipe', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['fkp_id'], ['fkp_complaints.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_fkp_status_logs_fkp_id'), table_name='fkp_status_logs')
    op.drop_table('fkp_status_logs')
    op.drop_index(op.f('ix_fkp_resolutions_fkp_id'), table_name='fkp_resolutions')
    op.drop_table('fkp_resolutions')
    op.drop_index(op.f('ix_fkp_documents_fkp_id'), table_name='fkp_documents')
    op.drop_table('fkp_documents')
    op.drop_index(op.f('ix_fkp_attachments_fkp_id'), table_name='fkp_attachments')
    op.drop_table('fkp_attachments')
    op.drop_index(op.f('ix_fkp_complaints_status'), table_name='fkp_complaints')
    op.drop_index(op.f('ix_fkp_complaints_nomor_fkp'), table_name='fkp_complaints')
    op.drop_index(op.f('ix_fkp_complaints_distributor_id'), table_name='fkp_complaints')
    op.drop_table('fkp_complaints')
    op.drop_index(op.f('ix_distributor_users_user_id'), table_name='distributor_users')
    op.drop_index(op.f('ix_distributor_users_distributor_id'), table_name='distributor_users')
    op.drop_table('distributor_users')
    op.drop_index(op.f('ix_distributors_kode_distributor'), table_name='distributors')
    op.drop_index(op.f('ix_distributors_area_id'), table_name='distributors')
    op.drop_table('distributors')
    op.drop_index(op.f('ix_kelurahan_kecamatan_id'), table_name='kelurahan')
    op.drop_table('kelurahan')
    op.drop_index(op.f('ix_area_provinces_provinsi_id'), table_name='area_provinces')
    op.drop_index(op.f('ix_area_provinces_area_id'), table_name='area_provinces')
    op.drop_table('area_provinces')
    op.drop_index(op.f('ix_kecamatan_kabupaten_kota_id'), table_name='kecamatan')
    op.drop_table('kecamatan')
    op.drop_index(op.f('ix_areas_kode_area'), table_name='areas')
    op.drop_table('areas')
    op.drop_index(op.f('ix_users_role_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_role_permissions_role_id'), table_name='role_permissions')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_kabupaten_kota_provinsi_id'), table_name='kabupaten_kota')
    op.drop_table('kabupaten_kota')
    op.drop_index(op.f('ix_roles_kode_role'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_provinsi_nama_provinsi'), table_name='provinsi')
    op.drop_table('provinsi')
    op.drop_index(op.f('ix_product_catalog_kode_produk'), table_name='product_catalog')
    op.drop_table('product_catalog')
    # ### end Alembic commands ###
