"""add_fkp_testimoni

Revision ID: e48ecff4c0c5
Revises: e90d34a80b8e
Create Date: 2026-05-23 11:50:35.086346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e48ecff4c0c5'
down_revision: Union[str, None] = 'e90d34a80b8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fkp_testimoni',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('fkp_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('rating_keseluruhan', sa.Integer(), nullable=False),
    sa.Column('rating_kecepatan', sa.Integer(), nullable=True),
    sa.Column('rating_komunikasi', sa.Integer(), nullable=True),
    sa.Column('rating_solusi', sa.Integer(), nullable=True),
    sa.Column('komentar', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('kritik_saran_tim', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('rating_aplikasi', sa.Integer(), nullable=True),
    sa.Column('kritik_saran_app', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('tipe_responden', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['fkp_id'], ['fkp_complaints.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    sa.UniqueConstraint('fkp_id', 'user_id', name='uq_testimoni_fkp_user'), 
    op.create_index(op.f('ix_fkp_testimoni_fkp_id'), 'fkp_testimoni', ['fkp_id'], unique=False)
    op.create_index(op.f('ix_fkp_testimoni_user_id'), 'fkp_testimoni', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fkp_testimoni_user_id'), table_name='fkp_testimoni')
    op.drop_index(op.f('ix_fkp_testimoni_fkp_id'), table_name='fkp_testimoni')
    op.drop_table('fkp_testimoni')
    # ### end Alembic commands ###
