"""add_outlet_scspv_new_roles_fkp_revision

Revision ID: e682f38b3809
Revises: e0f84e1eefa4
Create Date: 2026-04-14 11:20:22.008238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e682f38b3809'
down_revision: Union[str, None] = 'e0f84e1eefa4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apsm_sc_spv',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('apsm_user_id', sa.Uuid(), nullable=False),
    sa.Column('sc_spv_user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['apsm_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sc_spv_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_apsm_sc_spv_apsm_user_id'), 'apsm_sc_spv', ['apsm_user_id'], unique=False)
    op.create_index(op.f('ix_apsm_sc_spv_sc_spv_user_id'), 'apsm_sc_spv', ['sc_spv_user_id'], unique=True)
    op.create_table('rsm_apsm',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('rsm_user_id', sa.Uuid(), nullable=False),
    sa.Column('apsm_user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['apsm_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['rsm_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rsm_apsm_apsm_user_id'), 'rsm_apsm', ['apsm_user_id'], unique=True)
    op.create_index(op.f('ix_rsm_apsm_rsm_user_id'), 'rsm_apsm', ['rsm_user_id'], unique=False)
    op.create_table('outlets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('distributor_id', sa.Uuid(), nullable=False),
    sa.Column('kode_outlet', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('nama_toko', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('pemilik_toko', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False),
    sa.Column('tipe_toko', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('no_hp', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=True),
    sa.Column('kelurahan_id', sa.Integer(), nullable=True),
    sa.Column('alamat_lengkap', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('foto_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('pic_user_id', sa.Uuid(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['distributor_id'], ['distributors.id'], ),
    sa.ForeignKeyConstraint(['kelurahan_id'], ['kelurahan.id'], ),
    sa.ForeignKeyConstraint(['pic_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outlets_distributor_id'), 'outlets', ['distributor_id'], unique=False)
    op.create_index(op.f('ix_outlets_kode_outlet'), 'outlets', ['kode_outlet'], unique=True)
    op.create_table('sc_spv_distributors',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('sc_spv_user_id', sa.Uuid(), nullable=False),
    sa.Column('distributor_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['distributor_id'], ['distributors.id'], ),
    sa.ForeignKeyConstraint(['sc_spv_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sc_spv_distributors_distributor_id'), 'sc_spv_distributors', ['distributor_id'], unique=True)
    op.create_index(op.f('ix_sc_spv_distributors_sc_spv_user_id'), 'sc_spv_distributors', ['sc_spv_user_id'], unique=False)
    op.alter_column('fkp_attachments', 'uploaded_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=True)
    op.add_column('fkp_complaints', sa.Column('outlet_id', sa.Uuid(), nullable=True))
    op.add_column('fkp_complaints', sa.Column('catatan_sc_spv', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('fkp_complaints', sa.Column('catatan_rsm', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('fkp_complaints', sa.Column('catatan_direktur', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('fkp_complaints', sa.Column('catatan_qc', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('fkp_complaints', 'tanggal_pengajuan',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('fkp_complaints', 'tanggal_selesai',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.create_index(op.f('ix_fkp_complaints_outlet_id'), 'fkp_complaints', ['outlet_id'], unique=False)
    op.create_foreign_key(None, 'fkp_complaints', 'outlets', ['outlet_id'], ['id'])
    op.alter_column('fkp_resolutions', 'tanggal_pengiriman',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('fkp_status_logs', 'changed_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fkp_status_logs', 'changed_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('fkp_resolutions', 'tanggal_pengiriman',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_constraint(None, 'fkp_complaints', type_='foreignkey')
    op.drop_index(op.f('ix_fkp_complaints_outlet_id'), table_name='fkp_complaints')
    op.alter_column('fkp_complaints', 'tanggal_selesai',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('fkp_complaints', 'tanggal_pengajuan',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_column('fkp_complaints', 'catatan_qc')
    op.drop_column('fkp_complaints', 'catatan_direktur')
    op.drop_column('fkp_complaints', 'catatan_rsm')
    op.drop_column('fkp_complaints', 'catatan_sc_spv')
    op.drop_column('fkp_complaints', 'outlet_id')
    op.alter_column('fkp_attachments', 'uploaded_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_index(op.f('ix_sc_spv_distributors_sc_spv_user_id'), table_name='sc_spv_distributors')
    op.drop_index(op.f('ix_sc_spv_distributors_distributor_id'), table_name='sc_spv_distributors')
    op.drop_table('sc_spv_distributors')
    op.drop_index(op.f('ix_outlets_kode_outlet'), table_name='outlets')
    op.drop_index(op.f('ix_outlets_distributor_id'), table_name='outlets')
    op.drop_table('outlets')
    op.drop_index(op.f('ix_rsm_apsm_rsm_user_id'), table_name='rsm_apsm')
    op.drop_index(op.f('ix_rsm_apsm_apsm_user_id'), table_name='rsm_apsm')
    op.drop_table('rsm_apsm')
    op.drop_index(op.f('ix_apsm_sc_spv_sc_spv_user_id'), table_name='apsm_sc_spv')
    op.drop_index(op.f('ix_apsm_sc_spv_apsm_user_id'), table_name='apsm_sc_spv')
    op.drop_table('apsm_sc_spv')
    # ### end Alembic commands ###
