"""add percentage fields to fkp_resolution and fields qty_disetujui to fkpItem

Revision ID: e90d34a80b8e
Revises: 459bd026a44b
Create Date: 2026-05-19 16:40:00.291560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e90d34a80b8e'
down_revision: Union[str, None] = '459bd026a44b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fkp_items', sa.Column('qty_disetujui', sa.Integer(), nullable=True))
    op.add_column('fkp_resolutions', sa.Column('persentase_kompensasi_disetujui', sa.Integer(), nullable=True))
    op.add_column('fkp_resolutions', sa.Column('nilai_nota_penjualan', sa.Numeric(precision=15, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fkp_resolutions', 'nilai_nota_penjualan')
    op.drop_column('fkp_resolutions', 'persentase_kompensasi_disetujui')
    op.drop_column('fkp_items', 'qty_disetujui')
    # ### end Alembic commands ###
